version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - "./project:/project"
      - "./shortener.conf:/etc/nginx/conf.d/default.conf"
    links:
      - php
    container_name: web
  php:
    build: ./php-pdo
    restart: on-failure
    volumes:
      - "./project:/project"
    links:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=shortLinks
      - MYSQL_USER=root
      - MYSQL_DB_HOST=db
    container_name: php-fpm
  db:
    image: mysql:5.7
    user: "1000:50"
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=shortLinks
      - MYSQL_USER=root
    volumes:
      - "./database/mysql:/var/lib/mysql"
      - "./database/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    ports:
      - "3306:3306"
    container_name: mysql
  composer:
    image: composer
    volumes:
      - "./project:/app"
    command: install
    container_name: composer